version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  app:
    container_name: events_api
    build:
      context: .
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      PORT: 8000
      DB_CONN: "postgres://user:password@db:5432/db?sslmode=disable"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: adele

      
